In [1]:
import numpy as np
import pandas as pd
import pyodbc

In [1]:
from game import Game

In [2]:
test_game = Game()

Choose existing player or create a new one:
1.	Create a new player
2.	Sergei
>->->2

In [5]:
test_game.connection.populate_database(200)

In [11]:
question = test_game.connection.get_questions()

Enter number of questions: 50

 Categories:

0:	ANY
1:	Animals
2:	Art
3:	Celebrities
4:	Entertainment: Board Games
5:	Entertainment: Books
6:	Entertainment: Cartoon & Animations
7:	Entertainment: Comics
8:	Entertainment: Film
9:	Entertainment: Japanese Anime & Manga
10:	Entertainment: Music
11:	Entertainment: Musicals & Theatres
12:	Entertainment: Television
13:	Entertainment: Video Games
14:	General Knowledge
15:	Geography
16:	History
17:	Mythology
18:	Politics
19:	Science & Nature
20:	Science: Computers
21:	Science: Gadgets
22:	Science: Mathematics
23:	Sports
24:	Vehicles
Please choose your option: 0

 Difficulty:

0:	ANY
1:	Easy
2:	Hard
3:	Medium
Please choose your option: 0

 Type:

0:	ANY
1:	Multiple Choice
2:	True/False
Please choose your option: 0

In [5]:
question.head(5)

,category,correct_answer,difficulty,incorrect_answers,question,type
0,Mythology,Participating in cannibalism.,hard,"[Excessive mutilation of animal corpses., Perf...","According to Algonquian folklore, how does one...",multiple
1,Entertainment: Japanese Anime & Manga,'. . . the front tires slide so the car won't ...,hard,"['. . . the wheels lose traction, making the c...","In the anime Initial D, how does Takumi Fujiwa...",multiple
2,Entertainment: Video Games,Team Rocket,easy,"[Team Instinct, Team Valor, Team Mystic]",Which of these is NOT a team available in the ...,multiple
3,General Knowledge,Daniel Ek,medium,"[Sean Parker, Felix Miller, Michael Breidenbru...",Who is a co-founder of music streaming service...,multiple
4,Entertainment: Video Games,"December 24, 2004",medium,"[November 13, 2004, December 13, 2004, Novembe...","When was ""Garry's Mod"" released?",multiple

In [12]:
for _, q_series in question.iterrows():
    database.add_question2db(q_series)

START!!!
try to add question
Passing: 11
medium
multiple
Which of the following is NOT a quote from the 1942 film Casablanca?
added question
added answers
START!!!
try to add question
Passing: 23
hard
multiple
Which naval battle was considered the turning point of the Pacific Ocean Theater during World War 2?
added question
added answers
START!!!
try to add question
Passing: 9
medium
multiple
What name represents the letter "M" in the NATO phonetic alphabet?
added question
added answers
START!!!
try to add question
Passing: 9
easy
multiple
In the video-game franchise Kingdom Hearts, the main protagonist, carries a weapon with what shape?
added question
added answers
START!!!
try to add question
Passing: 12
easy
multiple
Which English guitarist has the nickname "Slowhand"?
added question
added answers
START!!!
try to add question
Passing: 12
easy
multiple
Which singer was featured in Jack Ü (Skrillex & Diplo)'s 2015 song 'Where Are Ü Now'?
added question
added answers
START!!!
try to add question
Passing: 9
medium
multiple
In the Morse code, which letter is indicated by 3 dots?
added question
added answers
START!!!
try to add question
Passing: 22
medium
multiple
Kuala Lumpur is the capital of which country?
added question
added answers
START!!!
try to add question
Passing: 23
medium
multiple
In what year was the last natural case of smallpox documented?
added question
added answers
START!!!
try to add question
Passing: 24
easy
boolean
In 2016, the United Kingdom voted to stay in the EU.
added question
added answers
START!!!
try to add question
Passing: 9
medium
multiple
In 2013 how much money was lost by Nigerian scams?
added question
added answers
START!!!
try to add question
Passing: 22
medium
multiple
The World Health Organization headquarters is located in which European country?
added question
added answers
START!!!
try to add question
Passing: 15
easy
multiple
In the 2002 video game "Kingdom Hearts", how many Keyblades are usable?
added question
added answers
START!!!
try to add question
Passing: 31
medium
multiple
In "Shakugan no Shana" what was the Shana usually referred as?
added question
added answers
START!!!
try to add question
Passing: 29
medium
multiple
What is the name of the main character in the webcomic Gunnerkrigg Court by Tom Siddell?
added question
added answers
START!!!
try to add question
Passing: 22
hard
multiple
What year is on the flag of the US state Wisconsin?
added question
added answers
START!!!
try to add question
Passing: 15
medium
boolean
In "Overwatch," an allied McCree will say "Step right up" upon using his ultimate ability Deadeye.
added question
added answers
START!!!
try to add question
Passing: 15
hard
multiple
In the game "Overwatch," which quote does the hero "McCree" NOT say upon using his flashbang ability?
added question
added answers
START!!!
try to add question
Passing: 9
medium
multiple
On average, Americans consume 100 pounds of what per second?
added question
added answers
START!!!
try to add question
Passing: 15
easy
multiple
Which of these characters is the mascot of the video game company SEGA?
added question
added answers
START!!!
try to add question
Passing: 11
easy
multiple
In the movie "Cast Away" the main protagonist's best friend while on the island is named
added question
added answers
START!!!
try to add question
Passing: 23
medium
multiple
What year did the Boxing Day earthquake & tsunami occur in the Indian Ocean?
added question
added answers
START!!!
try to add question
Passing: 29
medium
boolean
In the webcomic Homestuck, the first character introduced is Dave Strider.
added question
added answers
START!!!
try to add question
Passing: 9
easy
multiple
Which one of these is not a typical European sword design?
added question
added answers
START!!!
try to add question
Passing: 12
easy
multiple
The 2016 song "Starboy" by Canadian singer The Weeknd features which prominent electronic artist?
added question
added answers
START!!!
try to add question
Passing: 15
hard
multiple
Which Kingdom Hearts game featured the cast of "The World Ends With You"?
added question
added answers
START!!!
try to add question
Passing: 9
easy
multiple
According to Sherlock Holmes, "If you eliminate the impossible, whatever remains, however improbable, must be the..."
added question
added answers
START!!!
try to add question
Passing: 15
hard
multiple
In TF2 Lore, what are the names of the Heavy's younger sisters?
added question
added answers
START!!!
try to add question
Passing: 22
easy
multiple
Harvard University is located in which city?
added question
added answers
START!!!
try to add question
Passing: 9
easy
multiple
The New York Times slogan is, “All the News That’s Fit to…”
added question
added answers
START!!!
try to add question
Passing: 15
easy
boolean
The Konami Code is known as Up, Up, Down, Down, Left, Right, Right, Left, B, A, Start.
added question
added answers
START!!!
try to add question
Passing: 14
easy
multiple
Who won Big Brother 2014 UK?
added question
added answers
START!!!
try to add question
Passing: 14
easy
boolean
In Battlestar Galactica (2004), Cylons were created by man as cybernetic workers and soldiers.
added question
added answers
START!!!
try to add question
Passing: 15
easy
multiple
Valve Corporation is an American video game developer located in which city?
added question
added answers
START!!!
try to add question
Passing: 17
hard
multiple
Botanically speaking, which of these fruits is NOT a berry?
added question
added answers
START!!!
try to add question
Passing: 15
medium
multiple
Danganronpa Another Episode: Ultra Despair Girls is set after which Danganronpa game?
added question
added answers
START!!!
try to add question
Passing: 31
hard
multiple
In what year did the manga "Ping Pong" begin serialization?
added question
added answers
START!!!
try to add question
Passing: 15
medium
multiple
What is the perk that was introduced in the "Call Of Duty: Zombies" map, "Mob Of The Dead"?
added question
added answers
START!!!
try to add question
Passing: 14
hard
multiple
What was the callsign of Commander William Adama in Battlestar Galactica (2004)?
added question
added answers
START!!!
try to add question
Passing: 26
hard
multiple
Which school in Surrey, England did Steve Backshall attend?
added question
added answers
START!!!
try to add question
Passing: 19
medium
boolean
You can square root a negative number with an imaginary number "i".
added question
added answers
START!!!
try to add question
Passing: 12
hard
multiple
Björk's "Unison" contains a sample of which Oval song?
added question
added answers
START!!!
try to add question
Passing: 9
easy
multiple
Which of the following presidents is not on Mount Rushmore?
added question
added answers
START!!!
try to add question
Passing: 11
medium
multiple
What is Lilo's last name from Lilo and Stitch?
added question
added answers
START!!!
try to add question
Passing: 14
medium
multiple
Which WWF wrestler had the nickname "The Ayatollah of Rock 'N' Rolla"?
added question
added answers
START!!!
try to add question
Passing: 15
medium
multiple
In the "S.T.A.L.K.E.R." series, which of these items can't be used to lower the player's accumulated radiation?
added question
added answers
START!!!
try to add question
Passing: 15
medium
multiple
In the "Pikmin" series, what is the only pikmin type to possess visible ears?
added question
added answers
START!!!
try to add question
Passing: 31
hard
multiple
In the Overlord Anime who was Cocytus made by?
added question
added answers
START!!!
try to add question
Passing: 13
medium
multiple
The musical "Dirty Rotten Scoundrels" is set in what country?
added question
added answers
START!!!
try to add question
Passing: 32
hard
multiple
In the 1968 Cartoon Show "Wacky Races" what was the name of cavemen duo who rode in The Boulder Mobile?
added question
added answers

In [9]:
cursor = database.connection.cursor()

In [10]:
cursor.execute("SELECT * FROM Questions").fetchall()

[]

In [11]:
database.connection.close()

`

`

In [6]:
from dbengine import DBRequests

In [7]:
database = DBRequests()

In [3]:
# database.delete_db()

In [4]:
list_of_tables = [
    {'name': 'qCategories',
     'columns': [('CategoryID', 'SMALLINT', ' PRIMARY KEY'),
                 ('Category', 'VARCHAR(60)', 'NOT NULL')],
     'values': [(0, 'Any Category')]},

    {'name': 'qDifficulties',
     'columns': [('DifficultyID', 'VARCHAR(10)', 'PRIMARY KEY'),
                 ('Difficulty', 'VARCHAR(20)', 'NOT NULL')],
     'values': [('0', 'Any Difficulty'),
                ('easy', 'Easy'),
                ('medium', 'Medium'),
                ('hard', 'Hard')]},

    {'name': 'qTypes',
     'columns': [('TypeID', 'VARCHAR(10)', 'PRIMARY KEY'),
                 ('Type', 'VARCHAR(20)', 'NOT NULL')],
     'values': [('0', 'Mixed Types'),
                ('multiple', 'Multiple Choice'),
                ('boolean', 'True/False')]},

    {'name': 'Questions',
     'columns': [('QuestionID', 'INT', 'IDENTITY PRIMARY KEY'),
                 ('CategoryID', 'SMALLINT', 'FOREIGN KEY REFERENCES qCategories(CategoryID)'),
                 ('DifficultyID', 'VARCHAR(10)', 'FOREIGN KEY REFERENCES qDifficulties(DifficultyID)'),
                 ('TypeID', 'VARCHAR(10)', 'FOREIGN KEY REFERENCES qTypes(TypeID)'),
                 ('Question', 'VARCHAR(300)', 'NOT NULL UNIQUE')],
     'values': []},

    {'name': 'qAnswers',
     'columns': [('AnswerID', 'INT', 'IDENTITY PRIMARY KEY'),
                 ('QuestionID', 'INT', 'NOT NULL FOREIGN KEY REFERENCES Questions(QuestionID)'),
                 ('Answer', 'VARCHAR(99)', 'NOT NULL'),
                 ('IsCorrect', 'BIT', 'NOT NULL DEFAULT 0')],
     'values': []},

    {'name': 'Users',
     'columns': [('UserID', 'INT', 'IDENTITY PRIMARY KEY'),
                 ('UserName', 'VARCHAR(30)', 'NOT NULL')],
     'values': []},

    {'name': 'Games',
     'columns': [('GameID', 'INT', 'IDENTITY PRIMARY KEY'),
                 ('UserID', 'INT', 'FOREIGN KEY REFERENCES Users(UserID)'),
                 ('GameDate', 'DATE', 'NOT NULL CHECK (GameDate <= GETDATE())')],
     'values': []},

    {'name': 'GameResults',
     'columns': [('GameID', 'INT', 'FOREIGN KEY REFERENCES Games(GameID)'),
                 ('QuestionID', 'INT', 'FOREIGN KEY REFERENCES Questions(QuestionID)'),
                 ('AnswerID', 'INT', 'FOREIGN KEY REFERENCES qAnswers(AnswerID)')],
     'values': []},
]

In [5]:
database.initialize_basic_tables(list_of_tables)

In [6]:
database.get_categories_from_api()

In [7]:
voc = database.vocabulary
voc

{'categories': {'Any Category': 0,
  'General Knowledge': 9,
  'Entertainment: Books': 10,
  'Entertainment: Film': 11,
  'Entertainment: Music': 12,
  'Entertainment: Musicals & Theatres': 13,
  'Entertainment: Television': 14,
  'Entertainment: Video Games': 15,
  'Entertainment: Board Games': 16,
  'Science & Nature': 17,
  'Science: Computers': 18,
  'Science: Mathematics': 19,
  'Mythology': 20,
  'Sports': 21,
  'Geography': 22,
  'History': 23,
  'Politics': 24,
  'Art': 25,
  'Celebrities': 26,
  'Animals': 27,
  'Vehicles': 28,
  'Entertainment: Comics': 29,
  'Science: Gadgets': 30,
  'Entertainment: Japanese Anime & Manga': 31,
  'Entertainment: Cartoon & Animations': 32},
 'difficulties': {'0': 'Any Difficulty',
  'easy': 'Easy',
  'hard': 'Hard',
  'medium': 'Medium'},
 'types': {'0': 'Mixed Types',
  'boolean': 'True/False',
  'multiple': 'Multiple Choice'}}

In [39]:
n_questions = 10
cols = "QuestionID, CategoryID, DifficultyID, TypeID, Question"
sql_request_questions = f"""SELECT  TOP {n_questions} {cols}
                              FROM  Questions
                          ORDER BY  NEWID(); """

resp_df = pd.read_sql(sql_request_questions, database.connection)

In [26]:
import pandas as pd

In [40]:
resp_df

,QuestionID,CategoryID,DifficultyID,TypeID,Question
0,2293,12,hard,multiple,Chino Moreno is the lead singer of which alter...
1,688,31,medium,multiple,"Which of the stands from ""JoJo's Bizarre Adven..."
2,3249,15,hard,multiple,"In the indie farming game ""Stardew Valley"", wh..."
3,2009,9,medium,boolean,The vapor produced by e-cigarettes is actually...
4,1690,12,medium,multiple,Which rapper had an album that went double pla...
5,295,15,medium,multiple,"What is not a playable race in ""Final Fantasy ..."
6,401,15,easy,multiple,"What is the name of ""Team Fortress 2"" update, ..."
7,394,15,medium,boolean,"""Return to Castle Wolfenstein"" was the only ga..."
8,1482,15,hard,multiple,"In the ""Devil May Cry"" franchise, which game i..."
9,1306,17,hard,multiple,The 'Islets of Langerhans' is found in which h...

In [43]:
pd.DataFrame(respond, columns=['a','b','c','d','e'], )

ValueError: Shape of passed values is (10, 1), indices imply (10, 5)

In [47]:
import pandas as pd

tuples = ((1,2,3),(4,6,7),(7,3,6),(8,2,7),(4,6,3),(7,3,6))

columnlist = ['a','b','c']
df = pd.DataFrame.from_records(list(tuples), columns=columnlist)
print (df)

   a  b  c
0  1  2  3
1  4  6  7
2  7  3  6
3  8  2  7
4  4  6  3
5  7  3  6