In [22]:
import urllib.request
import json
import numpy as np
import pandas as pd
from html import unescape

In [2]:
class TriviaConnection:
    url_token_request = "https://opentdb.com/api_token.php?command=request"
    url_categories_request = "https://opentdb.com/api_category.php"
    difficulties = {'Easy': 'easy', 'Medium': 'medium', 'Hard': 'hard'}
    types = {'Multiple Choice': 'multiple', 'True/False': 'boolean'}

    @classmethod
    def get_token(cls):
        with urllib.request.urlopen(cls.url_token_request) as url:
            answer = json.loads(url.read().decode())
            if answer['response_code'] == 0:
                return answer['token']
            else:
                return False

    @classmethod
    def get_categories(cls):
        with urllib.request.urlopen(cls.url_categories_request) as url:
            answer = json.loads(url.read().decode())
            cat_dict = {}
            for rec in answer['trivia_categories']:
                cat_dict[rec['name']] = rec['id']
            return cat_dict

    @classmethod
    def get_questions(cls, request_url):
        with urllib.request.urlopen(request_url) as url:
            answer = json.loads(url.read().decode())
            if answer['response_code'] == 0:
                return pd.DataFrame(answer['results'])
            else:
                return None

    def __init__(self):
        self.token = TriviaConnection.get_token()
        self.categories = TriviaConnection.get_categories()

In [3]:
class UserInteraction:
    def __init__(self, header, options_dict):
        self.header = header
        self.options_dict = options_dict
        self.options_list = ['ANY'] + sorted(options_dict.keys())
        
        
     # Print to user available options, get his choice and try to interpretate it:
    def get_user_input(self):
        print('\n', self.header, '\n')
        
        for i, opt in enumerate(self.options_list):
            print(f"{i}:\t{opt}")

        user_answer = input('Please choose your option: ')
        
        try:
            return self.options_dict[self.options_list[int(user_answer)]]
    
        except (ValueError, KeyError, IndexError):
            return False

In [4]:
def compile_user_request(connection, n_questions=10):
    
    q_category = UserInteraction('Categories:', connection.categories).get_user_input()
    q_difficulty = UserInteraction('Difficulty:', connection.difficulties).get_user_input()
    q_type = UserInteraction('Type:', connection.types).get_user_input()
    q_token = connection.token

    pattern = f"https://opentdb.com/api.php?amount={n_questions}"
    
    if q_category:
        pattern += f"&category={q_category}"
    if q_difficulty:
        pattern += f"&difficulty={q_difficulty}"
    if q_type:
        pattern += f"&type={q_type}"
    if q_token:
        pattern += f"&token={q_token}"
    
    return pattern

In [8]:
def clear_html_symbols(target):
    if isinstance(target, str):
        return unescape(target)
    else:
        return [unescape(element) for element in target]

### Implementation

In [5]:
connection = TriviaConnection()

In [6]:
request_url = compile_user_request(connection, n_questions=20)

 Categories:

0:	ANY
1:	Animals
2:	Art
3:	Celebrities
4:	Entertainment: Board Games
5:	Entertainment: Books
6:	Entertainment: Cartoon & Animations
7:	Entertainment: Comics
8:	Entertainment: Film
9:	Entertainment: Japanese Anime & Manga
10:	Entertainment: Music
11:	Entertainment: Musicals & Theatres
12:	Entertainment: Television
13:	Entertainment: Video Games
14:	General Knowledge
15:	Geography
16:	History
17:	Mythology
18:	Politics
19:	Science & Nature
20:	Science: Computers
21:	Science: Gadgets
22:	Science: Mathematics
23:	Sports
24:	Vehicles
Please choose your option: 0

 Difficulty:

0:	ANY
1:	Easy
2:	Hard
3:	Medium
Please choose your option: 0

 Type:

0:	ANY
1:	Multiple Choice
2:	True/False
Please choose your option: 0

In [9]:
questions = connection.get_questions(request_url).applymap(clear_html_symbols)
questions

,category,correct_answer,difficulty,incorrect_answers,question,type
0,Sports,Jordan,medium,"[Benetton, Ferrari, Mercedes]",With which team did Michael Schumacher make hi...,multiple
1,History,Saigon,medium,"[Ho Chi Minh City, Hanoi, Hue]",What was the capital of South Vietnam before t...,multiple
2,Geography,"Portugal, Ireland, Italy, Greece, Spain",easy,"[Poland, Iceland, Italy, Greece, Serbia, Polan...","The derisive acronym ""PIIGS"" refers to which o...",multiple
3,History,Aristotle,medium,"[Socrates, Plato, King Philip]",Who tutored Alexander the Great?,multiple
4,Entertainment: Video Games,San Andreas,medium,"[San Fierro, Las Venturas, Vice City]",Which of these is not the name of a city in th...,multiple
5,History,Martin Van Buren,medium,"[John Adams, George Washington, James Monroe ]",Who was the first president born in the indepe...,multiple
6,Science: Computers,Graphics Processing Unit,medium,"[Gaming Processor Unit, Graphite Producing Uni...",What does the term GPU stand for?,multiple
7,Entertainment: Television,2010,medium,"[2001, 2007, 2012]",In which year did the British television serie...,multiple
8,Entertainment: Television,House Majority Whip,easy,"[Attorney General, President, Chief of Staff]","In season one of the Netflix political drama ""...",multiple
9,Science: Computers,False,easy,[True],Linux was first created as an alternative to W...,boolean
10,Entertainment: Video Games,False,easy,[True],Watch_Dogs 2 is a prequel.,boolean
11,Entertainment: Television,Taking his D'k tahg,medium,[Insulting and laughing at him at the dinner t...,Which of following is rude and dishonorable by...,multiple
12,Entertainment: Video Games,Monster Hunter Tri,hard,"[Monster Hunter Freedom Unite, Monster Hunter ...","Which game in the ""Monster Hunter"" series intr...",multiple
13,Entertainment: Video Games,The Pentagon Thief,easy,"[Hellhounds, Jumping Jacks, Napalm Zombie]","What is the boss round featured in the ""Call O...",multiple
14,Mythology,Narcissus,medium,"[Clotho, Atropos, Lachesis]",Which of the following is not one of the Greek...,multiple
15,Entertainment: Film,Ridley Scott,medium,"[Christopher Nolan, Michael Bay, James Cameron]","Who directed the movie ""Alien""?",multiple
16,Entertainment: Video Games,False,medium,[True],"""Return to Castle Wolfenstein"" was the only ga...",boolean
17,History,True,easy,[False],The French Kingdom helped the United States ga...,boolean
18,Entertainment: Music,60's,easy,"[50's, 40's, 30's]","The ""British Invasion"" was a cultural phenomen...",multiple
19,Entertainment: Video Games,Haley,hard,"[Abigail , Elliott, Lewis]","In the indie farming game ""Stardew Valley"", wh...",multiple

In [10]:
def ask_question(test):
    print(test.question)
    
    options = sorted([test.correct_answer] + test.incorrect_answers)
    
    print("\nPossible answers:")
    for i, opt in enumerate(options, 1):
        print(f"{i}:\t{opt}")
        
    user_answer = None
    
    while not user_answer:
        try:
            user_answer = int(input('>>>>> '))
            user_answer = None if user_answer - 1 not in range(len(options)) else user_answer
        except ValueError:
            print('Please enter the answer number')
    
    print('\n')
    return test.category, test.question, options[user_answer - 1], test.correct_answer

In [12]:
result_df = pd.DataFrame(columns=['category','question', 'user_answer', 'correct_answer'])

In [13]:
for i, test in questions.iterrows():
    print(f"Question {i+1}:\t", end='')
    category, question, user_answer, correct_answer = ask_question(test)
    result_df = result_df.append(
        {
            'category': category,
            'question': question,
            'user_answer': user_answer,
            'correct_answer': correct_answer
        },
        ignore_index=True)

Question 1:	With which team did Michael Schumacher make his Formula One debut at the 1991 Belgian Grand Prix?

Possible answers:
1:	Benetton
2:	Ferrari
3:	Jordan
4:	Mercedes
>>>>> 1


Question 2:	What was the capital of South Vietnam before the Vietnam War?

Possible answers:
1:	Hanoi
2:	Ho Chi Minh City
3:	Hue
4:	Saigon
>>>>> 1


Question 3:	The derisive acronym "PIIGS" refers to which of the following European countries and their economic statuses?

Possible answers:
1:	Poland, Iceland, Italy, Greece, Serbia
2:	Poland, Iceland, Italy, Greenland, Spain
3:	Portugal, Iceland, Ireland, Greece, Serbia
4:	Portugal, Ireland, Italy, Greece, Spain
>>>>> 3


Question 4:	Who tutored Alexander the Great?

Possible answers:
1:	Aristotle
2:	King Philip
3:	Plato
4:	Socrates
>>>>> 4


Question 5:	Which of these is not the name of a city in the Grand Theft Auto series?

Possible answers:
1:	Las Venturas
2:	San Andreas
3:	San Fierro
4:	Vice City
>>>>> 3


Question 6:	Who was the first president born in the independent United States?

Possible answers:
1:	George Washington
2:	James Monroe
3:	John Adams
4:	Martin Van Buren
>>>>> 2


Question 7:	What does the term GPU stand for?

Possible answers:
1:	Gaming Processor Unit
2:	Graphical Proprietary Unit
3:	Graphics Processing Unit
4:	Graphite Producing Unit
>>>>> 3


Question 8:	In which year did the British television series "The Bill" end?

Possible answers:
1:	2001
2:	2007
3:	2010
4:	2012
>>>>> 3


Question 9:	In season one of the Netflix political drama "House of Cards", what government position does Frank Underwood hold?

Possible answers:
1:	Attorney General
2:	Chief of Staff
3:	House Majority Whip
4:	President
>>>>> 1


Question 10:	Linux was first created as an alternative to Windows XP.

Possible answers:
1:	False
2:	True
>>>>> 1


Question 11:	Watch_Dogs 2 is a prequel.

Possible answers:
1:	False
2:	True
>>>>> 1


Question 12:	Which of following is rude and dishonorable by Klingon standards?

Possible answers:
1:	Insulting and laughing at him at the dinner table
2:	Punching him and taking his ship station position
3:	Reaching over and taking his meal
4:	Taking his D'k tahg
>>>>> 4


Question 13:	Which game in the "Monster Hunter" series introduced the monster "Gobul"?

Possible answers:
1:	Monster Hunter Freedom Unite
2:	Monster Hunter Frontier
3:	Monster Hunter Generations
4:	Monster Hunter Tri
>>>>> 2


Question 14:	What is the boss round featured in the "Call Of Duty: Zombies" map "Five"?

Possible answers:
1:	Hellhounds
2:	Jumping Jacks
3:	Napalm Zombie
4:	The Pentagon Thief
>>>>> 1


Question 15:	Which of the following is not one of the Greek Fates?

Possible answers:
1:	Atropos
2:	Clotho
3:	Lachesis
4:	Narcissus
>>>>> 4


Question 16:	Who directed the movie "Alien"?

Possible answers:
1:	Christopher Nolan
2:	James Cameron
3:	Michael Bay
4:	Ridley Scott
>>>>> 4


Question 17:	"Return to Castle Wolfenstein" was the only game of the Wolfenstein series where you don't play as William "B.J." Blazkowicz.

Possible answers:
1:	False
2:	True
>>>>> 1


Question 18:	The French Kingdom helped the United States gain their independence over Great Britain during the Revolutionary War.

Possible answers:
1:	False
2:	True
>>>>> 2


Question 19:	The "British Invasion" was a cultural phenomenon in music where British boy bands became popular in the USA in what decade?

Possible answers:
1:	30's
2:	40's
3:	50's
4:	60's
>>>>> 4


Question 20:	In the indie farming game "Stardew Valley", which NPC hates the "prismatic shard" item when received as a gift?

Possible answers:
1:	Abigail
2:	Elliott
3:	Haley
4:	Lewis
>>>>> 3

In [14]:
result_df

,category,question,user_answer,correct_answer
0,Sports,With which team did Michael Schumacher make hi...,Benetton,Jordan
1,History,What was the capital of South Vietnam before t...,Hanoi,Saigon
2,Geography,"The derisive acronym ""PIIGS"" refers to which o...","Portugal, Iceland, Ireland, Greece, Serbia","Portugal, Ireland, Italy, Greece, Spain"
3,History,Who tutored Alexander the Great?,Socrates,Aristotle
4,Entertainment: Video Games,Which of these is not the name of a city in th...,San Fierro,San Andreas
5,History,Who was the first president born in the indepe...,James Monroe,Martin Van Buren
6,Science: Computers,What does the term GPU stand for?,Graphics Processing Unit,Graphics Processing Unit
7,Entertainment: Television,In which year did the British television serie...,2010,2010
8,Entertainment: Television,"In season one of the Netflix political drama ""...",Attorney General,House Majority Whip
9,Science: Computers,Linux was first created as an alternative to W...,False,False
10,Entertainment: Video Games,Watch_Dogs 2 is a prequel.,False,False
11,Entertainment: Television,Which of following is rude and dishonorable by...,Taking his D'k tahg,Taking his D'k tahg
12,Entertainment: Video Games,"Which game in the ""Monster Hunter"" series intr...",Monster Hunter Frontier,Monster Hunter Tri
13,Entertainment: Video Games,"What is the boss round featured in the ""Call O...",Hellhounds,The Pentagon Thief
14,Mythology,Which of the following is not one of the Greek...,Narcissus,Narcissus
15,Entertainment: Film,"Who directed the movie ""Alien""?",Ridley Scott,Ridley Scott
16,Entertainment: Video Games,"""Return to Castle Wolfenstein"" was the only ga...",False,False
17,History,The French Kingdom helped the United States ga...,True,True
18,Entertainment: Music,"The ""British Invasion"" was a cultural phenomen...",60's,60's
19,Entertainment: Video Games,"In the indie farming game ""Stardew Valley"", wh...",Haley,Haley

In [26]:
q_type_mask = result_df.correct_answer.isin(('True', 'False'))

result_df['q_type'] = np.where(q_type_mask, 'True/False', 'Multiple Choice')
result_df['correct'] = result_df['user_answer'] == result_df['correct_answer']
result_df.head()

,category,question,user_answer,correct_answer,q_type,correct
0,Sports,With which team did Michael Schumacher make hi...,Benetton,Jordan,Multiple Choice,False
1,History,What was the capital of South Vietnam before t...,Hanoi,Saigon,Multiple Choice,False
2,Geography,"The derisive acronym ""PIIGS"" refers to which o...","Portugal, Iceland, Ireland, Greece, Serbia","Portugal, Ireland, Italy, Greece, Spain",Multiple Choice,False
3,History,Who tutored Alexander the Great?,Socrates,Aristotle,Multiple Choice,False
4,Entertainment: Video Games,Which of these is not the name of a city in th...,San Fierro,San Andreas,Multiple Choice,False