In [1]:
import numpy as np
import pandas as pd
import pyodbc

In [15]:
from game import Game

In [16]:
test_game = Game()

Choose existing player or create a new one:
1.	Create a new player
2.	Sergei
>->->2

In [17]:
question = test_game.connection.get_questions()

Enter number of questions: 1000

 Categories:

0:	ANY
1:	Animals
2:	Art
3:	Celebrities
4:	Entertainment: Board Games
5:	Entertainment: Books
6:	Entertainment: Cartoon & Animations
7:	Entertainment: Comics
8:	Entertainment: Film
9:	Entertainment: Japanese Anime & Manga
10:	Entertainment: Music
11:	Entertainment: Musicals & Theatres
12:	Entertainment: Television
13:	Entertainment: Video Games
14:	General Knowledge
15:	Geography
16:	History
17:	Mythology
18:	Politics
19:	Science & Nature
20:	Science: Computers
21:	Science: Gadgets
22:	Science: Mathematics
23:	Sports
24:	Vehicles
Please choose your option: 0

 Difficulty:

0:	ANY
1:	Easy
2:	Hard
3:	Medium
Please choose your option: 0

 Type:

0:	ANY
1:	Multiple Choice
2:	True/False
Please choose your option: 0

In [20]:
question

,category,correct_answer,difficulty,incorrect_answers,question,type
0,Entertainment: Cartoon & Animations,Scar,easy,"[Fred, Jafar, Vada]",Who was the villain of ''The Lion King''?,multiple
1,Science & Nature,False,easy,[True],Igneous rocks are formed by excessive heat and...,boolean
2,Entertainment: Cartoon & Animations,George Clooney,hard,"[Jay Leno, Matt Stone, Robert Smith]",Who played Stan's dog in the South Park episod...,multiple
3,Entertainment: Video Games,Galaxian,medium,"[Galactica, Space Invaders, Galactic Wars]","What was the game ""Galaga"" was a sequel to?",multiple
4,General Knowledge,Genesis,easy,"[Exodus, Leviticus, Numbers]",What is the first book of the Old Testament?,multiple
5,Entertainment: Video Games,"20,000",hard,"[10,000, 15,000, 25,000]","In the game ""The Sims"", how many Simoleons doe...",multiple
6,Science & Nature,Femur,easy,"[Scapula, Fibula, Ulna]",Which is the longest bone in the human body?,multiple
7,Science & Nature,Lift,medium,"[Thrust, Drag, Weight ]","In aeronautics, flaps and slats are used to co...",multiple
8,Science: Mathematics,False,medium,[True],The Pythagorean theorem states that the square...,boolean
9,General Knowledge,True,medium,[False],"""Typewriter"" is the longest word that can be t...",boolean
10,Entertainment: Board Games,Free Parking,easy,"[Go to Jail, Jail, The Electric Company]","On a standard Monopoly board, which square is ...",multiple
11,Animals,Goat,medium,"[Sheep, Camel, Llama]",Cashmere is the wool from which kind of animal?,multiple
12,Entertainment: Video Games,Unreal,easy,"[Unity, Game Maker: Studio, Cry Engine]",Which of these video game engines was made by ...,multiple
13,History,France,medium,"[Germany, Italy, Austria]",The Battle of the Somme in World War I took pl...,multiple
14,Celebrities,John,medium,"[Jeff, Jerald, Jason]",Donald J. Trump's Middle Name is...,multiple
15,History,Ethiopia,easy,"[Côte d’Ivoire, Congo, Namibia]",Which of the following African countries was m...,multiple
16,Entertainment: Video Games,Halo,easy,"[Opening Suite, Shadows, Suite Autumn]",What is the title of song on the main menu in ...,multiple
17,Entertainment: Music,12,easy,"[19, 21, 25]",Which of these is NOT the name of an album rel...,multiple
18,Entertainment: Video Games,True,hard,[False],"In ""Portal 2"", Cave Johnson started out Apertu...",boolean
19,Vehicles,True,easy,[False],The full English name of the car manufacturer ...,boolean
20,Entertainment: Japanese Anime & Manga,True,easy,[False],"In the ""Melancholy of Haruhi Suzumiya"" series,...",boolean
21,General Knowledge,A mall with high vacancy rates or low consumer...,medium,"[A mall with no stores, A mall that has been c...",What is a dead mall?,multiple
22,Entertainment: Japanese Anime & Manga,Yukine,easy,"[Karuha, Mineha, Mayu]",In the anime Noragami who is one of the main p...,multiple
23,History,Justinian I,hard,"[Constantine IV, Arcadius, Theodosius the Great]",The Hagia Sophia was commissioned by which emp...,multiple
24,Entertainment: Video Games,Bow,hard,"[Hammer, Heavy Bowgun, Light Bowgun]",Which of these weapon classes DO NOT appear in...,multiple
25,Entertainment: Music,True,medium,[False],EDM label Monstercat signs tracks instead of a...,boolean
26,Science: Computers,Command Line Interface,medium,"[Common Language Input, Control Line Interface...","In computing terms, typically what does CLI st...",multiple
27,Entertainment: Television,It's a Wonderful Life,hard,"[Message In A Bottle Show, To The Moon Baboon,...","In the TV Show ""Donkey Kong Country"", which ep...",multiple
28,General Knowledge,Brad's Drink,medium,"[Pepsin Pop, Carolina Cola, Pepsin Syrup]",What was the soft drink Pepsi originally intro...,multiple
29,Entertainment: Video Games,Auto,hard,"[Eddie, Tango, Rush]",Which character from the Mega Man series made ...,multiple
30,Entertainment: Video Games,Kirby's Adventure,easy,"[Kirby Super Star, Kirby's Dream Land 2, Kirby...",Which Kirby game first introduced Copy Abilities?,multiple
31,Science: Gadgets,Microsoft,medium,"[HTC, Oculus, Tobii]",Which company developed the Hololens?,multiple
32,Entertainment: Television,Kahless the Unforgettable,hard,"[Lady Lukara of the Great Hall, Molor the Unfo...","In ""Star Trek"", who was the founder of the Kli...",multiple
33,Entertainment: Japanese Anime & Manga,1992,medium,"[1989, 1990, 1994]","What year did ""Bishoujo Senshi Sailor Moon"" ai...",multiple
34,Entertainment: Video Games,Semper Fi,medium,"[Ring of Steel, Vendetta, Eviction]","What is the name of the first level in ""Call o...",multiple
35,Celebrities,Auction Hunters,medium,"[Ramsay's Kitchen Nightmares, Hotel Hell, Hell...",In which of these TV shows did the chef Gordon...,multiple
36,Geography,Port Louis,hard,"[Port Moresby, Port Vila, Port-au-Prince]",What is the capital of Mauritius?,multiple
37,Entertainment: Video Games,Purple,medium,"[Red, Yellow, Blue]","In Portal, what color is the Morality Core?",multiple
38,Entertainment: Video Games,Sonic the Hedgehog 3,medium,"[Sonic the Hedgehog 2, Sonic & Knuckles, Sonic...",Which Sonic the Hedgehog game introudced Knuck...,multiple
39,Geography,"Rome, Italy",easy,"[Barcelona, Spain, Berlin, Germany, London, En...","Where would you find the ""Spanish Steps""?",multiple
40,Entertainment: Music,Deftones,hard,"[Tool, Korn, Type O Negative]",Chino Moreno is the lead singer of which alter...,multiple
41,Art,The Starry Night,easy,"[Wheatfields with Crows, The Sower with Settin...",Which Van Gogh painting depicts the view from ...,multiple
42,Entertainment: Music,The Beatles,medium,"[Elvis Presley, Michael Jackson, Pink Floyd]",According to the RIAA: Which artist has sold t...,multiple
43,Geography,Luxembourg,medium,"[Montenegro, Liechtenstein, Andorra]",What is the name of the only remaining Grand D...,multiple
44,Politics,False,medium,[True],Jeb Bush was elected as Governor of Florida in...,boolean
45,Science & Nature,Eight,hard,"[Four, Two, Six]",How many protons are in an oxygen atom?,multiple
46,Entertainment: Music,New Musical Express,easy,"[New Metro Entertainment, Next Musical Enterpr...",Which music publication is often abbreviated t...,multiple
47,Science & Nature,Sneeze,hard,"[Cough, Yawn, Hiccup]",Autosomal-dominant Compelling Helio-Ophthalmic...,multiple
48,Entertainment: Board Games,20,easy,"[30, 15, 25]",What is the maximum level you can have in a si...,multiple
49,Geography,North Korea,hard,"[South Korea, Japan, China]",Which country is the Taedong River in?,multiple

In [21]:
question.category.apply(lambda x: voc['categories'][x])

0     32
1     17
2     32
3     15
4      9
5     15
6     17
7     17
8     19
9      9
10    16
11    27
12    15
13    23
14    26
15    23
16    15
17    12
18    15
19    28
20    31
21     9
22    31
23    23
24    15
25    12
26    18
27    14
28     9
29    15
30    15
31    30
32    14
33    31
34    15
35    26
36    22
37    15
38    15
39    22
40    12
41    25
42    12
43    22
44    24
45    17
46    12
47    17
48    16
49    22
Name: category, dtype: int64

In [79]:
def add_question2db(q_series, game, db_connection):
    
    cursor = db_connection.cursor()
    
    CategoryID = game.connection.categories[q_series['category']]
    DifficultyID = q_series['difficulty']
    TypeID = q_series['type']
    Question = q_series['question']    
    
    try:
       # Add question:
        SQL_Add_Question = """
                           INSERT INTO Questions
                                       (CategoryID, DifficultyID, TypeID, Question)
                                VALUES (?, ?, ?, ?);
                           """
        cursor.execute(SQL_Add_Question, CategoryID, DifficultyID, TypeID, Question)
        
        # Get QuestionID of this new question:
        QuestionID = cursor.execute("""
                                    SELECT QuestionID
                                      FROM Questions
                                     WHERE Question = ?
                                    """, Question).fetchval()
        
        # Add Answers:
        SQL_Add_qAnswer = """
                          INSERT INTO qAnswers
                                      (QuestionID, Answer, IsCorrect)
                                VALUES(?, ?, ?)
                          """
        # Add correct answer:
        cursor.execute(SQL_Add_qAnswer, QuestionID, q_series['correct_answer'], 1)
        
        # Add incorrect answers:
        for ans in q_series['incorrect_answers']:
            cursor.execute(SQL_Add_qAnswer, QuestionID, ans, 0)
        
        # If everything went without errors - commit changes:
        connection.commit()
    
    except pyodbc.IntegrityError:
        connection.rollback()

In [83]:
for _, q_series in question.iterrows():
    add_question2db(q_series, test_game, connection)

In [78]:
connection.close()

In [9]:
conn_string = """Driver=ODBC Driver 17 for SQL Server;
              Server=.\LENOVOSQLEXPRESS;
              Database=Trivia;
              Trusted_Connection=yes;"""

connection = pyodbc.connect(conn_string, autocommit=False)

In [117]:
connection.close()

In [124]:
try:
    connection.execute('SELECT 1').fetchval()
except pyodbc.ProgrammingError as ex:
    print(ex)

In [129]:
ttt = question.iloc[1,]

`

`

`

In [9]:
from dbengine import DBRequests

In [10]:
database = DBRequests()

In [3]:
# database.delete_db()

In [4]:
list_of_tables = [
    {'name': 'qCategories',
     'columns': [('CategoryID', 'SMALLINT', ' PRIMARY KEY'),
                 ('Category', 'VARCHAR(60)', 'NOT NULL')],
     'values': [(0, 'Any Category')]},

    {'name': 'qDifficulties',
     'columns': [('DifficultyID', 'VARCHAR(10)', 'PRIMARY KEY'),
                 ('Difficulty', 'VARCHAR(20)', 'NOT NULL')],
     'values': [('0', 'Any Difficulty'),
                ('easy', 'Easy'),
                ('medium', 'Medium'),
                ('hard', 'Hard')]},

    {'name': 'qTypes',
     'columns': [('TypeID', 'VARCHAR(10)', 'PRIMARY KEY'),
                 ('Type', 'VARCHAR(20)', 'NOT NULL')],
     'values': [('0', 'Mixed Types'),
                ('multiple', 'Multiple Choice'),
                ('boolean', 'True/False')]},

    {'name': 'Questions',
     'columns': [('QuestionID', 'INT', 'IDENTITY PRIMARY KEY'),
                 ('CategoryID', 'SMALLINT', 'FOREIGN KEY REFERENCES qCategories(CategoryID)'),
                 ('DifficultyID', 'VARCHAR(10)', 'FOREIGN KEY REFERENCES qDifficulties(DifficultyID)'),
                 ('TypeID', 'VARCHAR(10)', 'FOREIGN KEY REFERENCES qTypes(TypeID)'),
                 ('Question', 'VARCHAR(300)', 'NOT NULL UNIQUE')],
     'values': []},

    {'name': 'qAnswers',
     'columns': [('AnswerID', 'INT', 'IDENTITY PRIMARY KEY'),
                 ('QuestionID', 'INT', 'FOREIGN KEY REFERENCES Questions(QuestionID)'),
                 ('Answer', 'VARCHAR(99)', 'NOT NULL'),
                 ('IsCorrect', 'BIT', 'NOT NULL DEFAULT 0')],
     'values': []},

    {'name': 'Users',
     'columns': [('UserID', 'INT', 'IDENTITY PRIMARY KEY'),
                 ('UserName', 'VARCHAR(30)', 'NOT NULL')],
     'values': []},

    {'name': 'Games',
     'columns': [('GameID', 'INT', 'IDENTITY PRIMARY KEY'),
                 ('UserID', 'INT', 'FOREIGN KEY REFERENCES Users(UserID)'),
                 ('GameDate', 'DATE', 'NOT NULL CHECK (GameDate <= GETDATE())')],
     'values': []},

    {'name': 'GameResults',
     'columns': [('GameID', 'INT', 'FOREIGN KEY REFERENCES Games(GameID)'),
                 ('QuestionID', 'INT', 'FOREIGN KEY REFERENCES Questions(QuestionID)'),
                 ('AnswerID', 'INT', 'FOREIGN KEY REFERENCES qAnswers(AnswerID)')],
     'values': []},
]

In [5]:
database.initialize_basic_tables(list_of_tables)

In [6]:
database.get_categories_from_api()

In [13]:
voc = database.vocabulary
voc

{'categories': {'Any Category': 0,
  'General Knowledge': 9,
  'Entertainment: Books': 10,
  'Entertainment: Film': 11,
  'Entertainment: Music': 12,
  'Entertainment: Musicals & Theatres': 13,
  'Entertainment: Television': 14,
  'Entertainment: Video Games': 15,
  'Entertainment: Board Games': 16,
  'Science & Nature': 17,
  'Science: Computers': 18,
  'Science: Mathematics': 19,
  'Mythology': 20,
  'Sports': 21,
  'Geography': 22,
  'History': 23,
  'Politics': 24,
  'Art': 25,
  'Celebrities': 26,
  'Animals': 27,
  'Vehicles': 28,
  'Entertainment: Comics': 29,
  'Science: Gadgets': 30,
  'Entertainment: Japanese Anime & Manga': 31,
  'Entertainment: Cartoon & Animations': 32},
 'difficulties': {'0': 'Any Difficulty',
  'easy': 'Easy',
  'hard': 'Hard',
  'medium': 'Medium'},
 'types': {'0': 'Mixed Types',
  'boolean': 'True/False',
  'multiple': 'Multiple Choice'}}

In [11]:
import pyodbc

In [12]:
conn_string = """Driver=ODBC Driver 17 for SQL Server;
              Server=.\LENOVOSQLEXPRESS;
              Database=Trivia;
              Trusted_Connection=yes;"""

connection = pyodbc.connect(conn_string, autocommit=True)
cursor = connection.cursor()

In [18]:
connection.close()

In [13]:
cursor.execute('INSERT INTO ASDF VALUES (2,3,4)')

ProgrammingError: ('42S02', "[42S02] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid object name 'ASDF'. (208) (SQLExecDirectW)")

In [8]:
import json
import requests

In [9]:
response = requests.get("https://opentdb.com/api_category.php")
categories = json.loads(response.text)
categories

{'trivia_categories': [{'id': 9, 'name': 'General Knowledge'},
  {'id': 10, 'name': 'Entertainment: Books'},
  {'id': 11, 'name': 'Entertainment: Film'},
  {'id': 12, 'name': 'Entertainment: Music'},
  {'id': 13, 'name': 'Entertainment: Musicals & Theatres'},
  {'id': 14, 'name': 'Entertainment: Television'},
  {'id': 15, 'name': 'Entertainment: Video Games'},
  {'id': 16, 'name': 'Entertainment: Board Games'},
  {'id': 17, 'name': 'Science & Nature'},
  {'id': 18, 'name': 'Science: Computers'},
  {'id': 19, 'name': 'Science: Mathematics'},
  {'id': 20, 'name': 'Mythology'},
  {'id': 21, 'name': 'Sports'},
  {'id': 22, 'name': 'Geography'},
  {'id': 23, 'name': 'History'},
  {'id': 24, 'name': 'Politics'},
  {'id': 25, 'name': 'Art'},
  {'id': 26, 'name': 'Celebrities'},
  {'id': 27, 'name': 'Animals'},
  {'id': 28, 'name': 'Vehicles'},
  {'id': 29, 'name': 'Entertainment: Comics'},
  {'id': 30, 'name': 'Science: Gadgets'},
  {'id': 31, 'name': 'Entertainment: Japanese Anime & Manga'},
  {'id': 32, 'name': 'Entertainment: Cartoon & Animations'}]}